"""add_last_quantity

Revision ID: 8fc329ca5f3f
Revises: 4f219d4a4a6e
Create Date: 2023-12-26 20:21:54.384275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8fc329ca5f3f"
down_revision: Union[str, None] = "4f219d4a4a6e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("phone", sa.Column("last_quantity", sa.BigInteger(), nullable=True))
    op.execute("UPDATE phone SET last_quantity = 0 WHERE last_quantity IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("phone", "last_quantity")
    # ### end Alembic commands ###
